<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/controller/nosotrosController.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/controller/nosotros_portada_Controller.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/controller/directivaController.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/controller/miembrosController.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/controller/noticias_portada_Controller.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/controller/noticiasController.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/controller/sliderController.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/directive/directive.js"></script>
<script type="text/javascript" src="<?php  echo base_url(); ?>js/app/service/service.js"></script>